language: node_js

node_js :
    - "v4"
    - "v5"


addons:
    postgresql: "9.3"


before_script:
  - psql -f test/sql/create-db.sql -U postgres
  - psql -f test/sql/tables.sql -U postgres


sudo: false
